on:
  workflow_dispatch:
  pull_request:
    branches:
    - dev
    paths:
    - azsvcs/**
    - '**.tf'

jobs:
  get-modifications:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.modifications.outputs.modified }}
    steps:
    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      id: modifications
      with:
        token: ${{ github.token }}
  tf-check:
    needs: get-modifications
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ fromJSON(needs.get-modifications.outputs.modified) }}
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Terraform Format Check
      run: |
        terraform fmt -check