name: test-on-pr

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jasondemps1/scratch/.github/workflows/deploy-tf@feature/test1
      with:
        who-to-greet: 'me'